features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: 1
  logo: true
  name: true
  node_user_picture: true
  slogan: true
facebook_url: 'https://www.facebook.com/flashwebcenter'
twitter_url: 'https://twitter.com/flashwebcenter'
pinterest_url: 'https://www.pinterest.com/alaahaddad'
google_plus_url: 'https://plus.google.com/+Flashwebcenter'
linkedin_url: 'http://www.linkedin.com/company/flash-web-center'
instagram_url: 'https://www.instagram.com/flashwebcenter'
youtube_url: 'https://www.youtube.com/user/flashwebcenter'
drupal_url: 'https://www.drupal.org/u/flashwebcenter'
rss_url: rss.xml
copyright_text: 'Copyright 2020 - CC BY-NC-SA'
show_social_icon: 0
show_credit_link: 0
top_region: 1
main_region: 0
bottom_region: 1
footer_region: 1
_core:
  default_config_hash: dgz9gxPMcs1i9Iu9qsUxrYdLR_N-a74VDp9m5LThnjY
logo:
  use_default: 0
  path: 'public://kingdom-of-the-outlands.png'
favicon:
  use_default: 0
  path: 'public://favicon.ico'
  mimetype: image/vnd.microsoft.icon
website_width: ''
equal_width: 0
current_theme: w3-theme-green
color_page_wrapper: ''
color_header: ''
color_primary_menu: ''
color_welcome_text: ''
color_highlighted: ''
color_top_container: ''
color_top_first: ''
color_top_second: ''
color_top_third: ''
color_page_title: ''
color_main: ''
color_breadcrumb: ''
color_sidebar_first: ''
color_content: 'w3-link-blue-grey w3-link-blue-gray-hover'
color_sidebar_second: 'w3-link-blue-grey w3-link-dark-gray-hover'
color_bottom_container: ''
color_bottom_first: ''
color_bottom_second: ''
color_bottom_third: ''
color_bottom_forth: ''
color_footer_container: ''
color_footer_first: ''
color_footer_second: ''
color_footer_third: ''
color_footer_menu: ''
color_copyright: ''
